name: CI
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 8 * * 6'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p ~/dotfiles-install-dir
      - run: |
          ls spaceship-prompt
      - run: |
          HOME=~/dotfiles-install-dir ./install -v